run_tests:
  image: golang:1.23.5-alpine3.21
  script:
    - go build ./test_cicd.go

# build_n_push_image:
#   image: docker:latest
#   script:
#     - docker build -t zukidocker/oss:test_cicd-go .
#     - 
