variables:
  IMAGE_NAME: zukidocker/oss
  IMAGE_TAG: test_cicd-go

build_and_push_image:
  image: docker:latest
  services:
    - name: docker:dind
  before_script: docker login -u $DOCKER_USER -p $DOCKER_USER_PASSWD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
